<?php
/**
 * @var \Application\Users\Row $user
 * @var \Bluz\View\View $this
 */
?>

<h3 class="page-header">
    <?= __('Profile') ?>
    <?php if ($this->user()->id == $user->id) : ?>
        <?= $this->ahref(__('Change email'), ['users', 'change-email'], ['class' => 'btn btn-mini pull-right']) ?>
        <?= $this->ahref(__('Change password'), ['users', 'change-password'], ['class' => 'btn btn-mini pull-right']) ?>
    <?php endif; ?>
</h3>

<div class="panel-body">
    <div class="row">
        <div class="col-md-3 col-lg-3 " align="center">
            <a href="#" class="thumbnail">
                <img id="avatar" src="" alt="avatar">
            </a>
        </div>
        <div class=" col-md-9 col-lg-9 ">
            <table class="table table-user-information">
                <tbody>
                <tr>
                    <td><?= __('Email') ?></td>
                    <td><a href="mailto:<?= $user->email ?>"><?= $user->email ?></a></td>
                </tr>
                <tr>
                    <td><?= __('Status') ?></td>
                    <td><?= $user->status ?></td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

